### ISSUE TITLE
Lv. 92 Leatherworker - Using Rapid Synthesis over Groundwork

### ISSUE THREAD

**Issue by LayaReed** [dazemc/ffxiv-craft#19]
As the title says, the optimizer (set for 100% reliance, and before trying the Saiga Leather it was giving me 100% reliability) chooses Rapid Synthesis (50% chance) over Groundwork (100% chance). The stats are plenty enough that it shouldn't have to prioritize the first for CP conservation or anything.

Below are all the stats to how I found this issue:
Leather worker Lv. 92
- Craftsmanship: 4021
- Control: 3939
- CP: 589
- Tsai tou Vounou HQ

Saiga Leather was what I was trying to craft. Below was the suggested macro despite numerous retries (failed more than it really should, also I do have all the abilities up to lv. 92 and manipulation set as well so it's not missing any abilities.) The resulting Monte Carlo sim gives a success rate of 47.8%

/macrolock
/ac "Reflect" <wait.3>
/ac "Manipulation" <wait.2>
/ac "Delicate Synthesis" <wait.3>
/ac "Innovation" <wait.2>
/ac "Delicate Synthesis" <wait.3>
/ac "Basic Touch" <wait.3>
/ac "Standard Touch" <wait.3>
/ac "Byregot's Blessing" <wait.3>
/ac "Rapid Synthesis" <wait.3>
/echo Macro #1 complete <se.14>

Idk if this is purely a me error or if this might be something to look into for the optimizer. Hopefully I gave enough information for this. A side note, thank you guys for keeping this updated, its such an amazing resource. 

I also added the logs below if that also helps too.
[Execution Log FFXIV.txt](https://github.com/user-attachments/files/16115399/Execution.Log.FFXIV.txt)
[Monte Carlo Sim FFXIV.txt](https://github.com/user-attachments/files/16115400/Monte.Carlo.Sim.FFXIV.txt)
[Probalistic Sim FFXIV.txt](https://github.com/user-attachments/files/16115401/Probalistic.Sim.FFXIV.txt)

**Comment by LayaReed** [comment]
Side Comment: 
After doing my Saiga Leathers, I switched to Kumbhira Leather and Ophiotauros Leather, and the optimizer correctly chose groundwork instead of using rapid synthesis for both recipes (All stats, abilities, and foods were the exact same). 

For the Saiga Leathers I had redone the optimizer 5 times, including refreshing the page and I noticed it would suggest groundwork, but then get rid of it for rapid synthesis, hence me opening this issue. Hopefully this also is helpful information.

**Comment by LayaReed** [comment]
I apologize for the numerous comments and such, this will be the last comment, but I also have found that it happens with Alchemist and Lv. 83 recipes as well. My alchemist is 91 with the same stats and food and it still prioritizes rapid synthesis over groundwork (even first suggesting the latter then replacing with the lower efficiency rapid synthesis) even though I put a 100% reliance. It seems to be that the optimizer wants to prioritize the rapid synthesis' 500% efficiency rate over the recipe having a 100% reliance, so idk, hopefully all of these comments and initial post is helpful. I don't usually do issue/bug pages so if you have any comments on how to make it better let me know.

**Comment by dazemc** [comment]
Is there any particular reason you are using rapid synthesis? Genuinely curious because I was not aware they were being used. Any skills that are not at 100% success rate are really not feasible with the simulator. If you don't have rapid synthesis selected and it's showing up, that's a different story though.

**Comment by Vyadin** [comment]
This is happening to me as well. Level 99 CRP, solver set at 100% reliability, returns a macro that has ~52% reliability ending with Rapid Synthesis and 83 CP left over.

**Comment by LayaReed** [comment]
Honestly, until I was having this happen, I would just press the automated button for the abilities by level, manually add manipulation, and just go about my day and just tweak the crafting stats. Since I had the issues I have manually turned off rapid synthesis in the menu, didnt really think I would have to manually turn it off in order for it to not show. Never was a problem before 7.0 update for me so I never thought to.

**Comment by dazemc** [comment]
Only the '"Guaranteed" by level' actions are recommended right now because of the inherent complexity of branching multiple macros for condition and success rates. There have been changes to these skills that also have not been implemented and are low on the list of priorities. The option to choose actions at your level should be highlighted in green with "Recommended" next to it. Those actions are really only meant for manually solving.

Initial guess is also completely optional and I never use one.
