### ISSUE TITLE
Wrong tooltip on Delicate Synthesis

### ISSUE THREAD

**Issue by Fabricio20** [dazemc/ffxiv-craft#26]
Heyo, looks like the tooltip for Delicate Synthesis (level 94) is wrong, it says 100% Efficiency when it's actually 150%.

![image](https://github.com/user-attachments/assets/214e6cf3-18a1-4386-ba98-2fc57ce8cfbd)

![image](https://github.com/user-attachments/assets/fc555d75-eb6a-4869-bae6-e9c3e920fa5a)

Unless this is just showing quality efficiency?

**Comment by dazemc** [comment]
Yes I have been having a nightmare of a time debugging that one, I am aware of it. The backend has the appropriate numbers, it's just being displayed incorrectly. It's a UI bug.

**Comment by dazemc** [comment]
fixed
