### ISSUE TITLE
Finishing early for Fermented Aloe Juice

### ISSUE THREAD

**Issue by JimB123** [dazemc/ffxiv-craft#27]
Fermented Aloe Juice.

Level 93 CUL.  Craft 3796.  Control 3543.  CP 563.

Macro:
/macrolock
/micon Culinarian classjob
/ac "Muscle Memory" <wait.3>
/ac "Waste Not II" <wait.2>
/ac "Groundwork" <wait.3>
/ac "Preparatory Touch" <wait.3>
/ac "Preparatory Touch" <wait.3>
/ac "Preparatory Touch" <wait.3>
/ac "Delicate Synthesis" <wait.3>
/ac "Groundwork" <wait.3>
/echo Macro #1 complete <se.14>

Repeatedly finishes early and I have to spam Prudent Synthesis a few times to finish it off.

I also had another recipe finish early, didn't make a note of it though.

**Comment by dazemc** [comment]
can you paste in the execution log?

**Comment by JimB123** [comment]
You begin synthesizing a glass of fermented aloe juice.
You remove the following from your bag:
8 fire crystals
7 water crystals
4 bottles of grade 1 gemsap of dexterity 
1 Turali aloe leaf
1 Ut'ohmu tomato
You use Reflect  Success!
   Quality increases by 927.
   Durability decreases by 10.
You use Waste Not II  Success!
You use Groundwork  Success!
   Progress increases by 921.
   Durability decreases by 10.
You use Delicate Synthesis  Success!
   Progress increases by 256.
   Quality increases by 370.
   Durability decreases by 5.
You use Manipulation  Success!
You use Innovation  Success!
You use Preparatory Touch  Success!
   Quality increases by 1807.
   Durability decreases by 10.
You use Preparatory Touch  Success!
   Quality increases by 1390.
   Durability decreases by 10.
You use Byregot's Blessing  Success!
   Quality increases by 1891.
   Durability decreases by 5.
You use Groundwork  Success!
   Progress increases by 921.
   Durability decreases by 10.
Macro #1 complete <se.14>

Finished with only 2098/3375 progress

**Comment by JimB123** [comment]
Hmmm - looks like this doesn't match the macro.  Probably my issue.  closing this out.
