### ISSUE TITLE
Available Actions

### ISSUE THREAD

**Issue by Ichigo-Git** [dazemc/ffxiv-craft#28]
I am writing this using a translation site.
First of all, thank you for the useful site.
There may be a problem with my computer's browser settings, but even if I press "Available Actions" in the Crafter attribute, it does not save.
For example, if you press "Guaranteed by level...." in Carpenter and then do the same in Blacksmith and return to Carpenter, nothing will be selected.
Individually entered levels and Craftmanship values ​​are retained as entered.
I am using Chrome as my browser and cookies are enabled.
Are there any other items I should check?

**Comment by dazemc** [comment]
Hmm that is strange, I'm not experiencing that myself. If you press F12 and then press on the "Console" tab, you might be able to catch any errors that are happening. You can also try to force reload the site, hold on CTRL and press reload.

**Comment by dazemc** [comment]
Try to uninstall and reinstall chrome. If that doesn't work, export your settings from the crafting site and then clear the data for the site and import. That error is just related to the website icon and doesn't effect anything.

**Comment by Ichigo-Git** [comment]
Thank you for your many replies.
The result was not resolved. Here's what I did:
・Reinstall Chrome
・After exporting the configuration file, clear Chrome's cache and import it.
What I am concerned about is that Acrions is not retained in Edge as well.

**Comment by Ichigo-Git** [comment]
Thank you for your many replies.
The result was not resolved. Here's what I did:
・Reinstall Chrome
・After exporting the configuration file, clear Chrome's cache and import it.
What I am concerned about is that Acrions is not retained in Edge as well.

**Comment by dazemc** [comment]
Does the issue go away if you don't use your settings? If so, can you upload your settings?
