### ISSUE TITLE
Solver freezes with specific Available Action config

### ISSUE THREAD

**Issue by Zomoroko** [dazemc/ffxiv-craft#30]
After some testing, I figured out that having this specific configuration of Available Actions will cause the Solver to freeze when you press Start:
- Reflect enabled
- Careful Synthesis (Level 82) disabled
- Prudent Synthesis disabled
- Refined Touch Combo disabled
- Immaculate Mend disabled

As long as all 5 of these settings are in this state simultaneously, the solver will get stuck and not progress past 0/1000 once Start is pressed. This effectively makes the solver unusable for any crafting job between Levels 69-82.

**Comment by dazemc** [comment]
Mend actions weren't being checked before being used, fixed.
