### ISSUE TITLE
Pointless Trained Perfection added

### ISSUE THREAD

**Issue by emerald000** [dazemc/ffxiv-craft#32]
![firefox_AFIuRdCr7y](https://github.com/user-attachments/assets/ef09effe-1e2d-44ad-bf0b-53c1f12b79e9)

A pointless Trained Perfection is added to the initial guess which just makes the craft take longer for the same result. I understand having it as an option to iterate on, but it shouldn't be given as an output as it is just strictly worse.

**Comment by dazemc** [comment]
Then unselect trained perfection from the list of available skills

**Comment by emerald000** [comment]
While this would solve this exact situation, it removes the chance of finding a better solution that does use the skill. And while it was easy to see the skill being redundant since it didn't change from the input, I probably wouldn't have realized if I had gotten that answer from scratch.

**Comment by dazemc** [comment]
Ahhh okay I misunderstood. I can fix this fairly easily. Just to make sure though, you are saying you that since the macro sequence will already be 100/100 then you want a shorter macro sequence?

**Comment by emerald000** [comment]
In short, if two sequences are compared and they both have full progress and the same quality, the shorter sequence should be given as a solution. Of course the longer sequence can still be kept as a candidate for further evolution.

**Comment by dazemc** [comment]
Sorry took me longer than I expected but I just pushed an update that completely reworks how trained perfection is handled. I added a reward for sequences that use TP below 100% quality to encourage its use, it's only taken out if the quality is equal to or exceeds the max quality AND if it increases the total macro length.
