### ISSUE TITLE
Standard and advanced touch combos using full CP

### ISSUE THREAD

**Issue by BoredDan** [dazemc/ffxiv-craft#33]
So I was attempting to optimize from a currently working macro to both check the monte carlo and see if the optimizer could do better. Anyways the macro simply does not work in the simulator as the advanced touch combo was usinng the full 96 CP of the actions uncomboed instead of the 54 CP it should be using. I could add extra CP to compensate but that only works for the simulator and the optimizer would then potentially use more CP then I have available.

![image](https://github.com/user-attachments/assets/bb6ab9b3-ffe6-4610-99ab-183b5cb1800a)
![image](https://github.com/user-attachments/assets/4dffe9af-eda0-4773-a17c-fcb03e90fb6c)

**Comment by ZekeRyukai** [comment]
To be clear, the cost isn't calculated properly for the Solver or Simulator.

**Comment by dazemc** [comment]
fixed
