### ISSUE TITLE
Calculation discrepancy - Muscle Memory, Veneration, and Groundwork

### ISSUE THREAD

**Issue by ShiTsubasa** [dazemc/ffxiv-craft#38]
I've been running the calculator to set up macros as I don't always have time to sit down and run the math.  The macro creation seems to have some issue with some combination with Muscle Memory, Veneration, and Groundwork.  This is causing macros to finish the craft long before it should.  I'll post the calculator parse at the end, but here is issue I wish to highlight.

GSM 100
Attributes:  
Craftsmanship 4936
Control 4934 (4837 +97 food buff) 
CP 703 (611 +92 food buff)

[100] Rarefied Black Star Earrings
Base Progress - 263
Base Quality - 272

**Calculated Parse**
Muscle Memory - 789 (789)
Veneration
Manipulation
Waste Not II
Groundwork - 1972 (2761)

**Actual Run**
Muscle Memory - 789 (2761)
Veneration
Manipulation
Waste Not II
Groundwork - 2367 (3156)

The combination of the 3 bonuses seems to be the kicker as future uses of Groundwork parse correctly.  After running the numbers here is how I've found the game is running the calculation:

100% Efficiency on Progress at 263
Muscle Memory - 789 (add 100% buff to next Synthesis) (263 + 100% = 526)
Veneration - Add 50% efficiency to next Synthesis (4 steps) (526 + 50% = 789)
Manipulation - n/a
Waste Note II - n/a
Groundwork - 300% efficiency (789 + 300% = 2367)

I have not been able to replicate the value that the calculator parse is providing under any setup of the numbers I was able to think of.

Every other Synthesis event calculates properly.

This is the parse I got from the calculator.  I tried to set it up in a table but I couldn't find the markup to do so.  I also added the screenshot of the chatlog showing the numbers obtained from the run.

Monte   Carlo Random Example
--
==========================
Action                           DUR    CP        QUA      PRG    IQ     CTL  QINC  BPRG    BQUA   WAC       Cond     S/F
0                                   80   703          0        0     0    4934     0     0       0     0     Normal     0
1 Muscle Memory                     70   697          0      789    -1    4934     0   789       0    -1     Normal     1
2 Veneration                        70   679          0      789    -1    4934     0     0       0    -1     Normal     1
3 Manipulation                      70   583          0      789    -1    4934     0     0       0    -1     Normal     1
4 Waste Not II                      75   485          0      789    -1    4934     0     0       0    -1     Normal     1
5 Groundwork                        70   467          0     2761    -1    4934     0  1972       0    -1     Normal     1
6 Delicate Synthesis                70   435        272     3352     0    4934   272   591     272    -1     Normal     1
7 Preparatory Touch                 65   395        870     3352     2    4934   598     0     598    -1     Normal     1
8 Veneration                        70   377        870     3352     2    4934     0     0       0    -1     Normal     1
9 Groundwork                        65   359        870     4772     2    4934     0  1420       0    -1     Normal     1
10   Groundwork                          60   341      870       6192     2  4934       0  1420     0      -1     Normal     1
11   Innovation                          65   323      870       6192     2  4934       0     0     0      -1     Normal     1
12   Preparatory Touch                   55   283     1930       6192     4  4934    1060     0  1060      -1     Normal     1
13 Delicate   Synthesis                45   251       2542     6586     5    4934   612   394     612    -1     Normal     1
14   Observe                             45   244     2542       6586     5  4934       0     0     0      -1     Normal     1
15 Advanced   Touch                    35   226       3521     6586     6    4934   979     0     979    -1     Normal     1
16 Great   Strides                     35   194       3521     6586     6    4934     0     0       0    -1     Normal     1
17 Trained   Perfection                35   194       3521     6586     6    4934     0     0       0     0     Normal     1
18   Preparatory Touch                   35   154     5370       6586     8  4934    1849     0  1849       0     Normal     1
19 Great   Strides                     35   122       5370     6586     8    4934     0     0       0     0     Normal     1
20   Innovation                          35   104     5370       6586     8  4934       0     0     0       0     Normal     1
21   Preparatory Touch                   15    64     7954       6586     9  4934    2584     0  2584       0     Normal     1
22 Great   Strides                     15    32       7954     6586     9    4934     0     0       0     0     Normal     1
23 Byregot's   Blessing                 5     8      12034     6586     0    4934  4080     0    4080     0     Normal     1
24 Basic   Synthesis                   -5     8      12034     6901     0    4934     0   315       0     0     Normal     1
Progress   Check: true, Durability Check: true, CP Check: true, Tricks Check: true,   Reliability Check: true, Wasted Actions: 0

![ffxiv_08212024_175546_810](https://github.com/user-attachments/assets/921c7767-0ea6-47de-8a0a-819d8a347d6e)

**Comment by ShiTsubasa** [comment]
Here to add - It seems that the game isn't accounting for Groundwork Mastery either, so the number I gave is based on not having it, which is what the game is doing as well.

**Comment by ShiTsubasa** [comment]
Update: I did my math wrong, but overall the number was the same.  What the Optimizer was giving was not what I was getting at the time of craft.

**Comment by dazemc** [comment]
Just seen this I'll look into the optimizer later tomorrow

**Comment by ShiTsubasa** [comment]
Just ran a test and it seems to be working now.  Thank you!
