### ISSUE TITLE
Missing recepis for 7.1 Crafting/Gathering Gear

### ISSUE THREAD

**Issue by SzaryVek** [dazemc/ffxiv-craft#42]
Hey,

I believe the recipes for patch 7.1 Gear " Everseeker's" is missing in the solver.

**Comment by theconnstruct** [comment]
Also missing are the precrafts for those recipes: Alexandrian Plate, Optical Nanofiber, etc.

**Comment by Youtsax** [comment]
I'm also waiting for all these, any approx update time for it? :) Thank you for your hard work

**Comment by ZeroHimaa** [comment]
I could be wrong but it seems the xivapi search has been depracted so it is now scraping an old non updated database from xivapi.
there is a beta version of the api i think if someone wants to look at the xivapi_calls.py and update the code for it. out of my league.

**Comment by dazemc** [comment]
Yes I have to rewrite the API call for xivapi. I've been without power for the last few days due to weather and just got it back. I'll have it done within a day or so.

**Comment by SzaryVek** [comment]
Thanks, and please take as much time as you need.

**Comment by dazemc** [comment]
The beta of xivapi does not contain the needed data quite yet. This seems to be a consistent problem with this repo. I'm no longer going forward with using a 3rd party api, I'm working on using saintcoinach itself to datamine the relevant data. This should hopefully be a more long term solution but will take a little bit more time as I need to learn a little c#.

**Comment by dazemc** [comment]
Recipes have been updated but meals/meds are still being worked on
