### ISSUE TITLE
Level 84 Recipes - Durability/Difficulty Incorrect

### ISSUE THREAD

**Issue by Galilao77** [dazemc/ffxiv-craft#44]
The Red Pine Lumber recipe for a Lvl. 84 Carpenter is showing 80 durability, which should be 40, and 2900 Difficulty instead of 1450. Also found the same issue with some other Lvl. 84 recipes. Blacksmith/Armorer - Bismuth Ingot, Goldsmith - Phrygian Gold Ingot, Leatherworker - Saiga Leather, Weaver - Snow Linen, Culinarian - Garlean Cheese, and Culinarian - Coconut Milk.

**Comment by dazemc** [comment]
forgot to apply modifiers, just updated
