### ISSUE TITLE
Generates a new Build every day without any real changes

### ISSUE THREAD

**Issue by Michiocre** [dazemc/ffxiv-craft#5]
Currently your actions generate a new Build of the website every single day and the only change from the last day is a random version tag, see commits 651e197 and most of the other `automatic update` commits.

This value change is not needed at all.

A simple fix would be to remove the README.md file from the /lib/lvl-drag-drop/ .
Since this is the file that the jekyll-build-action rebuilds every time.

Another fix would be to exclude .md files from being build but i dont know enough about jekyll to know exactly what is needed.
Maybe something similar to this with a exlude instead of a include.
https://github.com/actions/jekyll-build-pages/issues/120#issuecomment-2004583746

Of course all of this is not needed if you dont mind creating a new commit and build every day.

**Comment by Michiocre** [comment]
For more info on the jekyll configs.
https://jekyllrb.com/docs/configuration/options/#global-configuration

**Comment by dazemc** [comment]
The gh actions trigger a script that pulls any new recipes, meals, or medicines and then pushes the updates to the repo. If there is no update to the data then it does nothing. A big issue in the past was maintainers that did not push these updates in a timely matter after patches. I chose this method as a middle ground between efficiency and laziness. Sure there is more efficient ways but this is a video game after all, not a business critical issue. Feel free to pr any improvements.

**Comment by dazemc** [comment]
finally got around to actually fixing this, sorry I had to take some time to learn a bit of yaml to handle the css cache key changes
