### ISSUE TITLE
new recipes

### ISSUE THREAD

**Issue by sagon528** [dazemc/ffxiv-craft#51]
any update when the new recipets will be added?

**Comment by dazemc** [comment]
which ones?

**Comment by sagon528** [comment]
The ones from 7.1 with Everseeker 720 crafting and gathering gear.  The dont come up when i look for them.

https://na.finalfantasyxiv.com/lodestone/topics/detail/9b42b2425f3a680caea3281ccd65c99677cb00e2

**Comment by dazemc** [comment]
They are 100% in there:
<img width="534" alt="Screenshot 2024-12-19 221527" src="https://github.com/user-attachments/assets/204eec01-4435-4f86-b795-6ee60a163601" />


You cannot craft anything that is more than 5 levels above your current level so make sure your crafter attributes are updated.
Try to press, SHIFT + F5 to clear the cached copy of the website.

**Comment by sagon528** [comment]
Ok i cleared my cache and now there showing up once i reset it.  sorry to bother, thx
