### ISSUE TITLE
Progress not correctly logged

### ISSUE THREAD

**Issue by kaldaren** [dazemc/ffxiv-craft#6]
I'm trying to do indagator gear, and I found that the progress is not correctly logged in the optimizer. I attached the picture of the rotation in Teamcraft. I used this particular rotation to successfully craft the indagator gear.

![image](https://github.com/dazemc/ffxiv-craft/assets/170971115/55a50bd0-c638-4675-80ed-286e6d88b653)
![image](https://github.com/dazemc/ffxiv-craft/assets/170971115/9b906e5f-f01d-41b6-9b33-dd47f6f1ddc4)

**Comment by dazemc** [comment]
You need to update your skills to reflect your current level. I was able to reproduce this by using level 72's Groundwork, you should be using level 86. Remember to click on the button with green text labelled "Guaranteed by Level (Recommended)" on the "Crafter Attributes" tab.

Working:
<img width="989" alt="test" src="https://github.com/dazemc/ffxiv-craft/assets/5232234/4cc18a10-f9c5-41e3-af1f-1c7881ac363c">

Using LVL 72 Groundwork:
<img width="998" alt="solved" src="https://github.com/dazemc/ffxiv-craft/assets/5232234/7404b080-9e2f-4be5-824c-bac9ae35225f">
